# Современные методы анализа данных и машинного обучения, БИ

## НИУ ВШЭ, 2025-26 учебный год

## Групповой проект №2. DE: Scraping & API

## Общая информация

__Дата выдачи:__ 24.03.2026

__Дедлайн по записи в таблицу:__ 4:00 29.03.2026

__Дедлайн по загрузке работ:__ 4:00 11.04.2026

__Защита проекта:__ 13.04.2026 - 15.04.2026

## Формат выполнения

Групповой проект представляет собой творческое инициативное групповое задание, которое выполняется студентами в командах от 3 до 6 человек. В то же время следует помнить, что чем больше в команде людей, тем выше предъявляются требования в целом к команде, а также к выполняемому ею проекту. Команды разрешается формировать из студентов разных групп.

При оценивании результатов выполнения проекта командой в обязательном порядке проверяется и учитывается в оценке вклад **каждого участника** в общую работу команды. Вследствие этого крайне важно ответственно подойти к выбору сокомандников, распределению обязанностей внутри команды, а также пресечению наличия "мертвых душ" в команде.

При необходимости команда большинством голосов имеет право исключить человека из команды **до загрузки работ** в систему [Anytask](https://anytask.org/), сообщив об этом преподавателю, в случае если такой человек никак не проявлялся в ходе выполнения проекта и являлся как раз таки той самой "мертвой душой". Помните про эту возможность, поскольку наличие "мертвых душ" может негативно повлиять на качество и оценку для всего проекта и, как следствие, в целом для всей команды!

Запись составов команд осуществляется по ссылке в таблице:

https://docs.google.com/spreadsheets/d/1t5GwRcerMBZVpmEDsT0Sm_fO4hlE4NJXnF0y2Uqa_iw/edit?usp=sharing

## Отправка материалов группового проекта

Во избежание использования при выполнении группового проекта генеративных моделей (ChatGPT и так далее) за рамками справочной и образовательной информации (то есть, например, для автоматической генерации кода по одному из этапов) **одному из участников команды** необходимо предварительно загрузить работу в систему [Anytask](https://anytask.org/). Наличие сгенерированного кода или любого другого случая "несанкционированного" использования нейросетей будет считаться плагиатом, и такой проект будет оценен в 0 баллов для всех участников. При отсутствии своевременно загруженных файлов с проектом команде также выставляется 0 за проект.

*Примечание: презентацию проекта загружать необязательно, важно отправить содержательные файлы с кодом и ссылку на репозиторий GitHub*

## Оценивание и штрафы

Групповой проект оценивается исходя из устной защиты (презентации) командой выполненного ими проекта перед комиссией. Комиссия составляется из преподавателей курса, ассистентов курса, а также приглашенных экспертов из индустрии.

В рамках каждой защиты комиссия выставляет два типа оценок.

Первая оценка — это оценка для всего проекта в целом. Она ставится комиссией, исходя из глубины проработки командой предметной области, сложности применяемых в проекте инструментов, а также прочих аспектов, связанных с содержанием выполняемого в проекте ТЗ. При выставлении этой оценки комиссия ориентируется на критерии, более подробно представленные ниже в разделе "Критерии оценки проекта".

Вторая оценка — это индивидуальная оценка каждого участника команды. Именно эта оценка выставляется впоследствии в ведомость. Индивидуальная оценка участника команды определяется комиссией, исходя из того, насколько участник ориентируется в выполненном командой проекте, как он отвечает на адресованные персонально ему вопросы комиссии, насколько в принципе прослеживается его роль в проекте, а также исходя из других аспектов, связанных с участием конкретного человека в деятельности команды. Индивидуальная оценка не может превосходить оценку команды за проект в целом (первую оценку), однако, в случае когда участник спокойно и корректно отвечает на все адресованные ему вопросы, свободно ориентируется в материале и содержании выполненного проекта, а также когда его роль в работе команды не вызывает сомнений, — в таком случае, индивидуальная оценка участника становится равной оценке для всего проекта (т.е. в идеальном случае — вторая оценка равна первой оценке). Кроме того, в исключительных случаях, при демонстрации участником на защите превосходящих ожидания уровней понимания, участия и вовлечения в рамках проекта, комиссия может своим решением повысить индивидуальную оценку для этого участника на 0,5 или 1 балл относительно общей оценки за проект (первой оценки).

Во избежание субъективности и/или предвзятости оценки тех или иных членов комиссии в отношении тех или иных команд, а также каких-либо иных проявлений неравных условий — распределение команд между комиссиями осуществляется абсолютно рандомно с использованием средств библиотеки Numpy :)) — в качестве рэндом сида выступает дата, в которую производится распределение, например, `np.random.seed(29032026)`.

Обратите, пожалуйста, внимание на то, что бОльшая часть комиссий осуществляет приём проектов в очной форме, однако могут присутствовать и 1-2 комиссии, которые будут работать дистанционно с использованием средств видеосвязи. В случае попадания команды путем случайного распределения в комиссию, работающую в очной форме, *не допускается* какое-либо изменение формата проведения для команды на онлайн-режим, равно как и любые другие перемещения команд между комиссиями (смены комиссий), для сохранения честности и непредвзятости случайного распределения.

Явка студента на защиту проекта является обязательной; вклад студента без его присутствия не оценивается и автоматически является равным нулю. Для дистанционных комиссий, дополнительным требованием является обязательное наличие включенной камеры в течение всего времени нахождения в конференции

## Описание задания

В современном мире данных эффективный сбор и интеграция информации из различных источников являются фундаментом для принятия обоснованных решений и успешного ведения бизнеса. Компании, стремясь к конкурентоспособности, активно используют технологии веб-скрапинга и взаимодействия с API для автоматизации процесса сбора данных, обеспечения их актуальности и полноты.

В данном проекте вы на реальных данных попрактикуетесь в том, как осуществляется веб-скрапинг различных сайтов для извлечения необходимой информации, а также в работе с API популярных сервисов для получения структурированных данных. Вы научитесь применять современные инструменты и библиотеки, отражающие различные этапы DE, обрабатывать и очищать полученную информацию, а также интегрировать данные из различных источников для последующего использования их в аналитических и бизнес-задачах.

### Постановка задачи

В рамках этого проекта вы сами найдете датасет, с которым будете работать. Точнее, не найдете, а... соберёте его самостоятельно на основе источников!

Итак, начните с того, что выберите два сайта/портала со схожей тематикой (например, NYT и Bloomberg). Их тематика должна позволять в дальнейшем объединить данные в единую таблицу. Один из этих двух сайтов нужно будет обработать с помощью средств Web-Scraping'a и Data Parsing'a; другой же — используя API.

Определившись с источниками, непосредственно проделайте скачивание данных путём скрейпинга и методами API соответственно и затем объедините всё в финальный датасет. Обязательным требованием к датасету является также наличие в нём как минимум одного столбца с текстовыми данными: описание, состав, комментарии о чём-либо, текст заметки/новости, или что-то ещё.

Кроме того, разумеется, следует помнить, что полученный датасет должен, конечно, быть осмысленным с бизнес-точки зрения и потенциально позволять решать какую-то конкретную бизнес-задачу. Это как минимум означает, что каждому объекту, имеющему своё признаковое пространство — в том числе с текстовым признаком, — должно также соответствовать значение некоторой целевой переменной, которая является релевантной в рамках выбранной вами предметной области.

Примеры задач, которые мы можем предложить вам в качестве источника для вдохновения — пожалуйста, ни в коем случае не воспринимайте это как исчерпывающий список — это действительно всего лишь примеры:

* Сайт новостей: текстовый столбец — сама новость; признаки — различные характеристики новости: автор, дата публикации, тип новости и т.д.; целевая переменная — количество просмотров новости (можно поделить на число дней с момента даты публикации, чтобы получить «среднее число просмотров в день», что ещё нагляднее)

* Сайт с товарами/книгами/фильмами: текстовый столбец — описание товара/книги/фильма; признаки — различные характеристики объекта: цена, год производства/выпуска, компания-производитель и т.д.; целевая переменная — средний рейтинг объекта

* Блоги: текстовый столбец — тексты заметок; признаки — различные характеристики заметки: автор, время публикации, количество прикрепленных изображений и т.д.; целевая переменная — число просмотров

* И любые другие ваши идеи, которые подходят под описанный выше формат

После сбора данных и объединения их в общий датасет, необходимо очистить его от мусора (в том числе, желательно с использованием регулярных выражений); посчитать различные статистики по собранным данным (в случае если столбец текстовый, то, например, посчитать частотности слов, выявляя наиболее частотные слова, и т.д.); а также в целом провести EDA в контексте той бизнес-задачи, которую мы потенциально хотим решить по полученному датасету. В конце сделать выводы из проделанной работы.

### Этапы проекта

Ниже для вашего удобства еще раз в краткой форме представляем примерные этапы реализации проекта:

- Выбор источников данных, в соответствии с требованиями, описанными выше
- Формулировка бизнес-задачи, которую могла бы хотеть решить компания/платформа, на основе собираемых данных
- Обоснование сформулированной бизнес-задачи
- Извлечение данных путём работы с API
- Извлечение данных путём скрейпинга и парсинга
- Первичная обработка данных (EDA)
- Получение и агрегация результатов, финальные выводы

### Общие требования к проекту

В качестве результата выполнения группового проекта ваша команда должна получить презентацию, а также репозиторий с кодом на GitHub. Демонстрация репозитория и защита презентации перед комиссией осуществляется в фиксированную дату.

Оформление презентации остаётся полностью на ваше усмотрение, но помните, что результат должен быть релевантен для демонстрации бизнес-заказчику — комиссию, принимающую вашу работу, правильнее всего воспринимать именно в таком качестве. Например, вставлять в презентацию строчки кода или злоупотреблять скринами блокнота не рекомендуется.

С точки зрения концепции выполнения проекта — вам необходимо принять на себя роль дата-инженеров: продумать идеологию получения и извлечения данных с платформы — и дата-аналитиков: соотнести бизнес-задачу с формулировками на языке данных и извлечь полезные инсайты из проделанной работы. А в конце, конечно, — презентовать всю эту красоту в понятном виде потенциальному заказчику.

Разумеется, чем сложнее и чем нетривиальнее будет ваша задача, а также чем глубже и чем осмысленнее будут выводы, извлечённые в рамках этой задачи, — тем выше окажется качество вашего проекта и тем выше он будет оценён!

### Полезные замечания и советы

- Графики и визуализации — это очень хорошо — все любят графики
- Следите за тем, чтобы все графики на слайдах можно было прочитать даже без ваших комментариев
- Не нужно делать просто текстовые слайды
- Стройте свой проект, исходя из того, что ваша цель — представить полезную информацию для бизнеса
- Любой хороший Data Scientist должен уметь работать в команде, поэтому распределение ваших усилий в проекте остается за вами

### Технические требования

Ниже чуть более детализированно будут представлены минимальные технические требования по всем основным этапам и составным частям выполняемого вами группового проекта.

#### Обязательный сбор данных через API

* Необходимо реализовать сбор данных через API для как минимум одного веб-сайта
* Как минимум часть функций API должны применяться с обязательной передачей API-ключа (не общедоступные API)
* При формировании датасета должно осуществляться **не менее 5** различных запросов к API
* Данный этап является обязательным, что означает, что без его полного выполнения ***нельзя получить оценку за проект выше 1***

#### Обязательный сбор данных посредством скрейпинга

* Необходимо реализовать сбор и парсинг данных через библиотеки `requests` / `bs4` и другие рассмотренные в рамках семинара для как минимум одного веб-сайта, отличного от веб-сайта из предыдущего пункта
* Получившийся датасет должен содержать **не менее 10 000** записей
* Для очистки и подготовки датасета рекомендуется использование регулярных выражений
* Данный этап является обязательным, что означает, что без его полного выполнения ***нельзя получить оценку за проект выше 1***

#### Разведочный анализ данных (EDA)

* Изучить особенности данных в рамках объединённого датасета:
  * Есть ли пропущенные значения? Сколько? Какова их доля от общего числа объектов для каждого конкретного признака? И, в целом, насколько ваш датасет “разрежен” в контексте пропущенных значений? Выдвинуть и (желательно) проверить гипотезу, что могут означать пропущенные значения? Осмысленно и аргументированно обработать пропуски.
  * Есть ли ошибочные  (например, отрицательный возраст или пятиметровый рост человека; 3-й класс в задаче бинарной классификации) значения (признаки, целевая переменная) в данных? Обработать их.
  * Есть ли выбросы в данных? По возможности обработать их.
* Изучить поведение каждого признака в отдельности, его связь с целевой переменной, а также попарные корреляции (в том числе и в особенности с таргетом). Визуализировать попарные распределения признаков и корреляции наиболее значимых.
* Построить подходящие сводные таблицы и прочие диаграммы.
* Если проведенный вами анализ позволяет сделать какие-либо выводы, постараться сформулировать их максимально глубоко и развернуто. Упомянуть, как можно задействовать в дальнейшем приобретенные вами на этом этапе знания в решаемой задаче.
* Осуществить и другие осмысленные действия в рамках процесса EDA.

#### GitHub и требования при использовании СКВ

*   Для выполнения задания вы должны создать проект на GitHub (один репозиторий на всю команду!)
*   Необходимо добавить в репозиторий `.gitignore` и не грузить в репозиторий лишние файлы
*   Необходимо добавить в репозиторий `README.md` с подробным описанием проекта. В этот файл также необходимо добавить подробное описание данных — описание признаков, их тип, количество объектов каждого класса (в задачах классификации), информацию о пропущенных значениях (в т.ч о типичных филлерах, если это не `nan`). Также добавляйте другие релевантные вашей задачи описательные характеристики данных. После чтения этого файла у человека со стороны не должно остаться никаких вопросов про данные
*   В репозитории проекта размещаются ноутбуки / скрипты со сбором данных
*   Коммиты делаются осмысленно, с понятными внешнему наблюдателю комментариями — что было сделано по факту
*   При разработке необходимо соблюдать [гитфлоу](https://www.umgum.com/gitlab-workflow)

#### Артефакты по окончании работы над проектом

* Ноутбуки / скрипты со сбором и извлечением данных
* Ноутбуки c осуществлением EDA
* Файл `.gitignore`
* Заполненный файл `README.md` в репозитории проекта на гитхабе со ссылкой на данные и их подробным описанием, с выводами о проведенном EDA

#### Логирование

* Для получения высоких баллов добавьте в ваш проект логирование. Потренируйтесь включать и выключать его через файл настроек, а также задавать уровень логирования через этот же файл (не в приложении)
* Запустите ваш код, чтобы сохранился файл с логами
* Про логи можно почитать [тут](https://habr.com/ru/companies/wunderfund/articles/683880/) и [тут](https://tproger.ru/articles/shpargalka-po-logirovaniju-na-python)

#### Библиотека Selenium

* Для получения высоких баллов используйте библиотеку Selenium при сборе данных
* Реализуйте имитацию работы пользователя через Selenium
* Про данную библиотеку можно почитать [тут](https://habr.com/ru/companies/selectel/articles/754674/) и [тут](https://happypython.ru/2022/11/27/selenium-chromedriver-find-elements/)

## Критерии оценки проекта

Оценка за групповой проект в целом — то есть первая из двух оценок — выставляется по 10 балльной шкале, исходя из 3 критериев. Также комиссия на своё усмотрение может добавить (но не снизить) некоторое количество бонусных баллов за рамками данных критериев.

Каждый из критериев будет перечислен и рассмотрен ниже.

### Критерий 1. Выбор задачи и EDA (до 3,5 баллов)

Данный критерий оценивает, насколько обоснованной и осмысленной получилась решаемая бизнес-задача; насколько полно был осуществлен переход от бизнес-задачи к пайплайну подготовки данных (насколько в реальности формируемый датасет соответствует исходной постановке задачи с точки зрения интересов компании и насколько может помочь в решении такой задачи); а также насколько корректными, объёмными и прикладными для бизнеса получились выявленные в ходе исследования инсайты.

### Критерий 2. GitHub (до 1 балла)

Данный критерий оценивает, насколько корректным и квалифицированным было применение средств системы контроля версий в проекте; насколько были выполнены представленные в задании требования по всем необходимым файлам и условиям в рамках работы с GitHub; а также насколько эффективно данная система в действительности использовалась командой для распараллеливания задач по проекту.

### Критерий 3. Инструменты извлечения данных (до 5,5 баллов)

Данный критерий оценивает техническую реализацию процесса сбора данных автоматизированным образом с сайтов и порталов. В рамках этого критерия будет рассматриваться спектр различных технических инструментов, внедрённых в проект; корректность, эффективность и правильность их применения; а также сложность и новизна алгоритмов, подходов и библиотек, применяемых к данным.

*__Важно:__ в случае оценки __1 балл и ниже__ за этот критерий — оценка за весь проект становится равна оценке за этот критерий.*

*По данному критерию можно получить __больше 1 балла__ только при условии применения как средств Data Scraping (автоматического считывания HTML-кода страниц с последующей его обработкой), так и средств API (получению данных с использованием официальных протоколов компании/портала). При этом средства Scraping и API следует применять к разным компаниям/порталам, но представленным в рамках одной и той же предметной области (бизнес-задачи).*

*По данному критерию можно получить **3 балла и выше** только при условии использования в проекте логирования __ИЛИ__ библиотеки Selenium.*

*По данному критерию можно получить **4 балла и выше** только при условии использования в проекте логирования __И__ библиотеки Selenium.*

*По данному критерию можно получить **5 баллов и выше** только при условии использования в проекте логирования, библиотеки Selenium и, кроме этого, обоснованного применения дополнительных инструментов/подходов/библиотек, не упомянутых ранее в этом ноутбуке и не рассматривавшихся в рамках соответствующего семинара.*

In [131]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data1 =  pd.read_csv('final_dataset_api.csv')
data2 =  pd.read_csv('final_scraping_dataset_10000.csv')
data = pd.merge(data1, data2, on='name', how='left')
data

,Unnamed: 0,id,name,released,dataset_label,source_window,slug,rating,ratings_count,reviews_count,...,stores,developers,publishers,steam_review_percent,steam_review_count,steam_review_label,steam_price_text,steam_discount_pct,steam_platform_flags,steam_app_id
0,0,3498,Grand Theft Auto V,2013-09-17,released,2013,grand-theft-auto-v,4.47,7363,7499,...,"Steam, PlayStation Store, Epic Games, Xbox 360...","Rockstar North, Rockstar Games",Rockstar Games,79.0,56707.0,Mostly Positive,$14.99,50.0,win,3240220
1,1,3328,The Witcher 3: Wild Hunt,2015-05-18,released,2015,the-witcher-3-wild-hunt,4.64,7178,7297,...,"GOG, PlayStation Store, Steam, Xbox Store, Nin...",CD PROJEKT RED,CD PROJEKT RED,96.0,234151.0,Overwhelmingly Positive,$29.99,NaN,win,292030
2,2,4200,Portal 2,2011-04-18,released,2011,portal-2,4.58,6086,6143,...,"Xbox Store, Steam, PlayStation Store, Xbox 360...",Valve Software,"Electronic Arts, Valve",98.0,169118.0,Overwhelmingly Positive,$5.79,NaN,"linux, win",620
3,3,4291,Counter-Strike: Global Offensive,2012-08-21,released,2012,counter-strike-global-offensive,3.57,3634,3671,...,"PlayStation Store, Steam, Xbox 360 Store","Valve Software, Hidden Path Entertainment",Valve,86.0,2513715.0,Very Positive,Free,NaN,"linux, win",730
4,4,5286,Tomb Raider (2013),2013-03-05,released,2013,tomb-raider,4.06,4091,4125,...,"Xbox 360 Store, Steam, PlayStation Store, Goog...",Crystal Dynamics,Square Enix,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,19244,Silverfall: Earth Awakening,2008-07-18,released,2008,silverfall-earth-awakening,3.00,16,16,...,Steam,Monte Cristo,Focus Home Interactive,72.0,95.0,Mostly Positive,41 руб,85.0,win,4470
9996,9996,38567,Mabinogi,2008-03-27,released,2008,mabinogi,3.40,15,15,...,Steam,"NEXON KOREA, devCAT","Nexon, Nexon America",100.0,11.0,Positive,200 руб,NaN,music,509081
9997,9997,21418,Age of Booty,2008-10-15,released,2008,age-of-booty,3.80,15,15,...,"Xbox 360 Store, Steam, Xbox Store",Certain Affinity™,Capcom,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9998,9998,5309,Sudoku,2008-07-11,released,2008,sudoku,2.48,23,23,...,"PlayStation Store, Nintendo Store, Steam, App ...","Electronic Arts, 1C Wireless, Taranau Aliaksei...","Electronic Arts, SlyGames, Taranau Aliaksei, R...",80.0,15.0,Positive,170 руб,15.0,"mac, win",4215050
9999,9999,13536,Portal,2007-10-09,released,2007,portal,4.49,5007,5052,...,"Steam, Google Play","Valve Software, NVIDIA Lightspeed Studios","Valve, Buka Entertainment, NVIDIA, CyberFront",98.0,81012.0,Overwhelmingly Positive,385 руб,NaN,"linux, win",400

In [133]:
data['steam_price_text'].unique()

array(['$14.99', '$29.99', '$5.79', 'Free', nan, '$23.99', '$7.49',
       '$19.99', '$49.99', '$11.99', '$6.49', '$9.99', '$44.99', '$10.77',
       '$2.24', '$10.49', '$5.99', '$12.99', '$2.99', '$39.99', '$4.99',
       '$0.79', '$7.99', '$15.99', '$59.99', '$31.99', '$4.19', '$1.99',
       '$17.99', '$6.59', '$20.99', '$2.37', '$1.19', '$6.64', '$8.25',
       '$5.84', '$5.25', '$9.89', '$8.29', '$47.99', '$22.99', '$3.74',
       '$26.99', '$34.99', '$18.99', '$1.49', '$6.75', '$1.01', '$2.62',
       '$40.28', '$12.49', '$8.99', '$25.99', '$5.24', '$5.59', '$1.79',
       '$3.60', '$3.29', '$3.77', '$5.62', '$3.99', '$10.59', '$10.09',
       '$13.99', '$24.99', '$9.49', '$10.11', '$1.44', '$27.99', '$7.79',
       '$1.59', '$2.39', '$2.31', '$11.49', '$4.49', '$22.49', '$3.49',
       '$14.28', '$0.74', '$10.99', '$13.19', '$6.99', '$32.78', '$35.99',
       '$13.49', '$6.29', '$2.87', '$7.97', '$2.09', '$1.63', '$3.37',
       '$69.99', '$13.00', '$1.36', '$17.00', '$0.57', '$10.19', '$1.89',
       '$0.99', '$33.99', '$2.69', '$32.99', '$9.39', '$0.46', '$8.49',
       '$1.04', '$1.57', '$7.29', '$9.74', '$19.79', '$0.00', '$7.34',
       '$11.00', '$12.24', '$5.49', '$2.81', '$9.29', '$3.59', '$16.23',
       '$41.99', '$0.49', '$9.59', '$1.64', '$4.39', '$0.44', '$30.09',
       '$6.47', '$2.49', '$7.42', '$25.49', '$12.59', '$6.39', '$1.15',
       '$10.47', '$0.89', '165 руб', '799 руб', '710 руб', '490 руб',
       '385 руб', '599 руб', '200 руб', '879 руб', '1199 руб', '349 руб',
       '88 руб', '399 руб', '999 руб', '309 руб', '82 руб', '195 руб',
       '249 руб', '649 руб', '419 руб', '449 руб', '880 руб', '177 руб',
       '550 руб', '460 руб', '61 руб', '99 руб', '1100 руб', '739 руб',
       '1999 руб', '125 руб', '104 руб', '1500 руб', '21 руб', '42 руб',
       '104,10 руб', '1699 руб', '169 руб', '152 руб', '351 руб',
       '2199 руб', '1300 руб', '198 руб', '280 руб', '259 руб', '308 руб',
       '122 руб', '844,79 руб', '1299 руб', '133 руб', '424,20 руб',
       '782 руб', '299 руб', '1799 руб', '899 руб', '119 руб', '549 руб',
       '484 руб', '240 руб', '650 руб', '1499 руб', '389 руб', '300 руб',
       '199 руб', '995 руб', '209 руб', '392 руб', '70,56 руб',
       '3579 руб', '435 руб', '515 руб', '87 руб', '559 руб', '800 руб',
       '465 руб', '359 руб', '539 руб', '360 руб', '966 руб', '27 руб',
       '799,50 руб', '760,80 руб', '699 руб', '30 руб', '289 руб',
       '459 руб', '34 руб', '1900 руб', '1599 руб', '1650 руб', '400 руб',
       '74 руб', '129 руб', '144 руб', '2299 руб', '189 руб', '62 руб',
       '620 руб', '1296 руб', '499 руб', '137 руб', '1249 руб', '170 руб',
       '1929 руб', '149 руб', '590 руб', '842 руб', '941 руб', '1620 руб',
       '55 руб', '52 руб', '355 руб', '1399 руб', '49 руб', '1059 руб',
       '425 руб', '89 руб', '3999 руб', '815 руб', '1879 руб', '625 руб',
       '749 руб', '725 руб', '2300 руб', '750 руб', '440 руб', '59 руб',
       '1146 руб', '1135 руб', '154 руб', '339 руб', '275 руб',
       '2279 руб', '545 руб', '40 руб', '35 руб', '175 руб', '2240 руб',
       '500 руб', '743,49 руб', '1429 руб', '659,60 руб', '950,40 руб',
       '610 руб', '239,70 руб', '629 руб', '239 руб', '22 руб', '719 руб',
       '46 руб', '41 руб', '680 руб', '805 руб', '279 руб', '142 руб',
       '71 руб', '1139 руб', '350 руб', '220 руб', '96 руб', '1090 руб',
       '565 руб', '115 руб', '108 руб', '849 руб', '1099 руб', '79 руб',
       '68 руб', '420 руб', '69 руб', '579,75 руб', '319 руб', '665 руб',
       '950 руб', '889 руб', '920 руб', '600 руб', '1600 руб', '2000 руб',
       '3499 руб', '83 руб', '379 руб', '377 руб', '31 руб', '3599 руб',
       '1370 руб', '765 руб', '174 руб', '200,70 руб', '265 руб',
       '686 руб', '540 руб', '102 руб', '619 руб', '990 руб', '210 руб',
       '2749 руб', '1200 руб', '70 руб', '316,80 руб', '194 руб',
       '622 руб', '320 руб', '695 руб', '232 руб', '257 руб', '850 руб',
       '1655 руб', '227 руб', '700 руб', '140 руб', '28 руб', '38 руб',
       '809 руб', '1675 руб', '3322 руб', '660 руб', '334 руб', '90 руб',
       '86 руб', '25 руб', '29 руб', '163 руб', '605 руб', '32 руб',
       '418,50 руб', '186 руб', '428,40 руб', '120 руб', '205 руб',
       '100 руб', '192 руб', '760 руб', '1019 руб', '855 руб',
       '362,25 руб', '372 руб', '411 руб', '434 руб', '219 руб',
       '390 руб', '130 руб', '197 руб', '830 руб', '900 руб', '1297 руб',
       '450 руб', '352 руб', '1000 руб', '429 руб', '261 руб', '2799 руб',
       '980 руб', '1439,10 руб', '839 руб', '2878,56 руб', '77 руб',
       '33 руб', '72 руб', '1130 руб', '315 руб', '664,20 руб',
       '1124,70 руб', '$3.14', '$0.55', '$21.99', '$1.12', '$16.99',
       '$0.90', '$0.95', '$8.80', '$4.79', '$42.99', '475 руб', '223 руб',
       '1050 руб', '732 руб', '132 руб', '424 руб', '1150 руб', '340 руб',
       '369 руб', '1549 руб', '25,80 руб', '157 руб', '217 руб',
       '1489 руб', '103 руб', '290 руб', '92 руб', '1475 руб', '1649 руб',
       '1259 руб', '54 руб', '564,81 руб', '282 руб', '715 руб', '50 руб',
       '1012 руб', '677 руб', '80 руб', '1165 руб', '1085 руб',
       '1735,20 руб', '1390 руб', '1330 руб', '724,89 руб', '66 руб',
       '3049 руб', '3165 руб', '962,20 руб', '24 руб', '44 руб',
       '780 руб', '139 руб', '160 руб', '65 руб', '112 руб', '86,10 руб',
       '176 руб', '1899 руб', '1398 руб', '36 руб', '1374 руб',
       '1850 руб', '869 руб', '374,40 руб', '123 руб', '604,50 руб',
       '297 руб', '127 руб', '1209 руб', '492 руб', '734 руб', '890 руб',
       '609 руб', '248 руб', '1480 руб', '1510 руб', '2869 руб',
       '685 руб', '150 руб', '1760 руб', '3299 руб', '1587 руб',
       '486,20 руб', '810 руб', '520 руб', '277 руб', '1711 руб',
       '21,78 руб', '930 руб', '655,35 руб', '254,70 руб', '1449 руб',
       '1586,70 руб', '213 руб', '615 руб', '56 руб', '2399 руб',
       '1350 руб', '633,60 руб', '188 руб', '39 руб', '558 руб',
       '395 руб', '1238 руб', '106 руб', '241,50 руб', '$0.65', '$26.12',
       '$0.76', '$16.71', '$199.99', '$6.24', '$13.59', '$22.48',
       '$19.33', '$0.71', '$19.78', '$50.96', '$13.58', '$18.73', '$9.98',
       '$19.98', '$8.74', '$21.18', '$8.40', '$24.80', '690 руб',
       '57 руб', '305 руб', '293 руб', '480 руб', '180 руб', '3565 руб',
       '2400 руб', '1529 руб', '410 руб', '409 руб', '64 руб', '2999 руб',
       '532 руб', '2849 руб', '101 руб', '114 руб', '1223,10 руб',
       '2139 руб', '741 руб', '655 руб', '1035 руб', '2068,50 руб',
       '252,45 руб', '612 руб', '2100 руб', '597,10 руб', '350,25 руб',
       '640 руб', '309,50 руб', '269 руб', '58 руб', '23 руб',
       '1087,20 руб', '1875 руб', '1419,20 руб', '1054 руб', '134 руб',
       '2769 руб', '218 руб', '250 руб', '253 руб', '43 руб',
       '630,40 руб', '413 руб', '539,60 руб', '2659 руб', '329 руб',
       '542 руб', '5000 руб', '1569 руб', '570 руб', '636 руб', '806 руб',
       '2439 руб', '304 руб', '26 руб', '872,10 руб', '2499 руб',
       '321 руб', '147 руб', '225 руб', '679 руб', '1750 руб', '2099 руб',
       '335 руб', '116 руб', '105 руб', '2200 руб', '1126,25 руб',
       '224 руб', '469,80 руб', '124 руб', '357 руб', '1800 руб',
       '509,58 руб', '1005 руб', '51 руб', '4999 руб', '1700 руб',
       '110 руб', '1333 руб', '671,40 руб', '745 руб', '630 руб',
       '2109 руб', '179 руб', '2990 руб', '4392 руб', '140,77 руб',
       '1920 руб', '939 руб', '653 руб', '514,25 руб', '136 руб',
       '647 руб', '519 руб', '468 руб', '803 руб', '330 руб', '575 руб',
       '251,20 руб', '720 руб', '2690 руб', '669 руб', '3199 руб',
       '212 руб', '1550 руб', '98 руб', '344 руб', '291 руб', '1400 руб',
       '203 руб', '709 руб', '379,95 руб', '1290 руб', '455 руб',
       '649,50 руб', '472 руб', '427,70 руб', '1125 руб', '442,40 руб',
       '704,29 руб', '891,75 руб', '658 руб', '1140 руб', '312 руб',
       '1395 руб', '905 руб', '260 руб', '637 руб', '1786,50 руб',
       '444 руб', '1767,20 руб', '457 руб', '747 руб', '522 руб',
       '546 руб', '1055 руб', '1280 руб', '2600 руб', '222 руб',
       '809,58 руб', '426,40 руб', '495 руб', '548 руб', '10000 руб',
       '173 руб', '215 руб', '426 руб', '1857 руб', '415 руб',
       '1764,95 руб', '299,99 руб', '667,80 руб', '602,65 руб',
       '1528 руб', '370,45 руб', '2192,96 руб', '247,60 руб',
       '705,75 руб', '284 руб', '250,60 руб', '329,99 руб', '1168 руб',
       '1269 руб', '145 руб', '407 руб', '1539 руб', '787,50 руб',
       '1408,50 руб', '812 руб', '348 руб', '639 руб', '1944 руб',
       '121 руб', '506 руб', '4198 руб', '2594,77 руб', '325 руб',
       '104,65 руб', '93 руб', '292 руб', '1520 руб', '1560 руб',
       '1463 руб', '1040 руб', '126 руб', '689 руб', '599,99 руб',
       '138 руб', '380,70 руб', '439 руб', '365 руб', '208 руб',
       '1049 руб', '568 руб', '2500 руб', '1490 руб', '216 руб',
       '1540 руб', '346,85 руб', '287 руб', '4295 руб', '1950 руб',
       '560 руб', '2309 руб', '226 руб', '363 руб', '2891 руб',
       '1190 руб', '566,10 руб', '1119 руб', '687 руб', '899,10 руб',
       '333,90 руб', '910 руб', '425,70 руб', '525 руб', '557 руб',
       '748 руб', '585 руб', '623 руб', '113 руб', '326 руб', '367 руб',
       '3659 руб', '944,10 руб', '2317 руб', '4821 руб', '4900 руб',
       '1088,10 руб', '635 руб', '1438,56 руб', '1424 руб', '127,40 руб',
       '820 руб', '2149 руб', '865,80 руб', '397,60 руб', '1309 руб',
       '73 руб', '368 руб', '1235 руб', '704 руб', '2436 руб', '580 руб',
       '3900 руб', '262 руб', '4400 руб', '909 руб', '391 руб',
       '3200 руб', '274 руб', '659 руб', '471,14 руб', '256 руб',
       '404 руб', '6500 руб', '109 руб', '229 руб', '1004,50 руб',
       '37 руб'], dtype=object)

Мы видим, что на данный момент с ценами нельзя работать, поскольку они все строчные, к тому же в разной валюте. Стим установил курс доллара 76 рублей, будем исходить из него. Изменим цены таким образом, чтобы все значения были числовыми и измерялись в долларах, кроме этого на некоторые игры в моменте была скидка, поэтому мы вернем цену к начальному, базовому значению, нивелировав скидку

In [136]:
data['steam_price_text']

0        $14.99
1        $29.99
2         $5.79
3          Free
4           NaN
         ...
9995     41 руб
9996    200 руб
9997        NaN
9998    170 руб
9999    385 руб
Name: steam_price_text, Length: 10000, dtype: object

In [138]:
def unify_price(s):
    if pd.isna(s):
        return s
    elif s[0] == '$':
        return float(s[1:])
    elif s[-3:] == 'руб':
        s = s.replace(',', '.')
        return np.round(float(s[:-3]) / 76, 2)
    elif s == 'Free':
        return 0
    else:
        return s

In [140]:
data['steam_price_text'] = data['steam_price_text'].apply(unify_price)

In [141]:
data['steam_price_text'] = np.where(data['steam_discount_pct'] > 0, np.round(data['steam_price_text'] / (1 - data['steam_discount_pct'] / 100), 2), data['steam_price_text'])
data

,Unnamed: 0,id,name,released,dataset_label,source_window,slug,rating,ratings_count,reviews_count,...,stores,developers,publishers,steam_review_percent,steam_review_count,steam_review_label,steam_price_text,steam_discount_pct,steam_platform_flags,steam_app_id
0,0,3498,Grand Theft Auto V,2013-09-17,released,2013,grand-theft-auto-v,4.47,7363,7499,...,"Steam, PlayStation Store, Epic Games, Xbox 360...","Rockstar North, Rockstar Games",Rockstar Games,79.0,56707.0,Mostly Positive,29.98,50.0,win,3240220
1,1,3328,The Witcher 3: Wild Hunt,2015-05-18,released,2015,the-witcher-3-wild-hunt,4.64,7178,7297,...,"GOG, PlayStation Store, Steam, Xbox Store, Nin...",CD PROJEKT RED,CD PROJEKT RED,96.0,234151.0,Overwhelmingly Positive,29.99,NaN,win,292030
2,2,4200,Portal 2,2011-04-18,released,2011,portal-2,4.58,6086,6143,...,"Xbox Store, Steam, PlayStation Store, Xbox 360...",Valve Software,"Electronic Arts, Valve",98.0,169118.0,Overwhelmingly Positive,5.79,NaN,"linux, win",620
3,3,4291,Counter-Strike: Global Offensive,2012-08-21,released,2012,counter-strike-global-offensive,3.57,3634,3671,...,"PlayStation Store, Steam, Xbox 360 Store","Valve Software, Hidden Path Entertainment",Valve,86.0,2513715.0,Very Positive,0.00,NaN,"linux, win",730
4,4,5286,Tomb Raider (2013),2013-03-05,released,2013,tomb-raider,4.06,4091,4125,...,"Xbox 360 Store, Steam, PlayStation Store, Goog...",Crystal Dynamics,Square Enix,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,19244,Silverfall: Earth Awakening,2008-07-18,released,2008,silverfall-earth-awakening,3.00,16,16,...,Steam,Monte Cristo,Focus Home Interactive,72.0,95.0,Mostly Positive,3.60,85.0,win,4470
9996,9996,38567,Mabinogi,2008-03-27,released,2008,mabinogi,3.40,15,15,...,Steam,"NEXON KOREA, devCAT","Nexon, Nexon America",100.0,11.0,Positive,2.63,NaN,music,509081
9997,9997,21418,Age of Booty,2008-10-15,released,2008,age-of-booty,3.80,15,15,...,"Xbox 360 Store, Steam, Xbox Store",Certain Affinity™,Capcom,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9998,9998,5309,Sudoku,2008-07-11,released,2008,sudoku,2.48,23,23,...,"PlayStation Store, Nintendo Store, Steam, App ...","Electronic Arts, 1C Wireless, Taranau Aliaksei...","Electronic Arts, SlyGames, Taranau Aliaksei, R...",80.0,15.0,Positive,2.64,15.0,"mac, win",4215050
9999,9999,13536,Portal,2007-10-09,released,2007,portal,4.49,5007,5052,...,"Steam, Google Play","Valve Software, NVIDIA Lightspeed Studios","Valve, Buka Entertainment, NVIDIA, CyberFront",98.0,81012.0,Overwhelmingly Positive,5.07,NaN,"linux, win",400

In [142]:
data.duplicated().sum()

0

In [143]:
data.isna().sum()

Unnamed: 0                 0
id                         0
name                       0
released                   0
dataset_label              0
source_window              0
slug                       0
rating                     0
ratings_count              0
reviews_count              0
playtime                   0
added                      0
suggestions_count          0
genres                     0
tags                     176
platforms                  0
stores                     0
developers                36
publishers                86
steam_review_percent    2076
steam_review_count      2076
steam_review_label      2076
steam_price_text        1973
steam_discount_pct      9183
steam_platform_flags    1819
steam_app_id            1819
dtype: int64

In [146]:
data = data.drop(columns=['steam_discount_pct', 'id', 'steam_app_id', 'Unnamed: 0', 'developers', 'platforms', 'reviews_count', 
                         'dataset_label', 'stores', 'added', 'rating', 'name', 'steam_review_label', 'slug', 'ratings_count'])

удаляем steam_discount_pct потому что столбец 91% пустой и не несет прикоадного смысла для анализа

In [151]:
df = data.dropna(subset=['steam_review_percent','steam_review_count','steam_price_text','steam_platform_flags','tags',
'publishers'])

In [152]:
df

,released,source_window,playtime,suggestions_count,genres,tags,publishers,steam_review_percent,steam_review_count,steam_price_text,steam_platform_flags
0,2013-09-17,2013,74,450,Action,"Singleplayer, Steam Achievements, Multiplayer,...",Rockstar Games,79.0,56707.0,29.98,win
1,2015-05-18,2015,43,688,"Action, RPG","Singleplayer, Full controller support, Atmosph...",CD PROJEKT RED,96.0,234151.0,29.99,win
2,2011-04-18,2011,11,570,"Shooter, Puzzle","Singleplayer, Steam Achievements, Multiplayer,...","Electronic Arts, Valve",98.0,169118.0,5.79,"linux, win"
3,2012-08-21,2012,64,607,Shooter,"Steam Achievements, Multiplayer, Full controll...",Valve,86.0,2513715.0,0.00,"linux, win"
5,2009-11-17,2009,9,613,"Action, Shooter","Singleplayer, Steam Achievements, Multiplayer,...","Electronic Arts, Valve, Akella",97.0,225402.0,5.79,"linux, win"
...,...,...,...,...,...,...,...,...,...,...,...
9994,2008-07-28,2008,1,552,"Action, Strategy","Multiplayer, Steam Cloud, First-Person, FPS, F...",Empires,86.0,1050.0,0.00,"linux, win"
9995,2008-07-18,2008,1,612,RPG,"Singleplayer, Multiplayer, RPG, Action RPG, Ha...",Focus Home Interactive,72.0,95.0,3.60,win
9996,2008-03-27,2008,2,532,"Action, Adventure, RPG, Simulation, Casual, Ma...","Singleplayer, Multiplayer, Great Soundtrack, R...","Nexon, Nexon America",100.0,11.0,2.63,music
9998,2008-07-11,2008,1,123,"Strategy, Board Games, Casual, Card, Education...","Singleplayer, Steam Achievements, 2D, puzzles,...","Electronic Arts, SlyGames, Taranau Aliaksei, R...",80.0,15.0,2.64,"mac, win"
9999,2007-10-09,2007,4,306,"Action, Puzzle","Singleplayer, Steam Achievements, Atmospheric,...","Valve, Buka Entertainment, NVIDIA, CyberFront",98.0,81012.0,5.07,"linux, win"

In [153]:
df['has_win'] = df['steam_platform_flags'].str.contains('win').replace([True, False], [1, 0])
df['has_mac'] = df['steam_platform_flags'].str.contains('mac').replace([True, False], [1, 0])
df['has_linux'] = df['steam_platform_flags'].str.contains('linux').replace([True, False], [1, 0])

C:\Users\1\AppData\Local\Temp\ipykernel_17768\1143600185.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['has_win'] = df['steam_platform_flags'].str.contains('win').replace([True, False], [1, 0])
C:\Users\1\AppData\Local\Temp\ipykernel_17768\1143600185.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['has_win'] = df['steam_platform_flags'].str.contains('win').replace([True, False], [1, 0])
C:\Users\1\AppData\Local\Temp\ipykernel_17768\1143600185.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['has_mac'] = df['steam_platform_flags'].str.contains('mac').replace([True, False], [1, 0])
C:\Users\1\AppData\Local\Temp\ipykernel_17768\1143600185.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['has_mac'] = df['steam_platform_flags'].str.contains('mac').replace([True, False], [1, 0])
C:\Users\1\AppData\Local\Temp\ipykernel_17768\1143600185.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['has_linux'] = df['steam_platform_flags'].str.contains('linux').replace([True, False], [1, 0])
C:\Users\1\AppData\Local\Temp\ipykernel_17768\1143600185.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['has_linux'] = df['steam_platform_flags'].str.contains('linux').replace([True, False], [1, 0])

In [155]:
df = df[df['has_win'] == 1]
df = df.drop('steam_platform_flags', axis=1)
df

,released,source_window,playtime,suggestions_count,genres,tags,publishers,steam_review_percent,steam_review_count,steam_price_text,has_win,has_mac,has_linux
0,2013-09-17,2013,74,450,Action,"Singleplayer, Steam Achievements, Multiplayer,...",Rockstar Games,79.0,56707.0,29.98,1,0,0
1,2015-05-18,2015,43,688,"Action, RPG","Singleplayer, Full controller support, Atmosph...",CD PROJEKT RED,96.0,234151.0,29.99,1,0,0
2,2011-04-18,2011,11,570,"Shooter, Puzzle","Singleplayer, Steam Achievements, Multiplayer,...","Electronic Arts, Valve",98.0,169118.0,5.79,1,0,1
3,2012-08-21,2012,64,607,Shooter,"Steam Achievements, Multiplayer, Full controll...",Valve,86.0,2513715.0,0.00,1,0,1
5,2009-11-17,2009,9,613,"Action, Shooter","Singleplayer, Steam Achievements, Multiplayer,...","Electronic Arts, Valve, Akella",97.0,225402.0,5.79,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,2008-09-19,2008,1,520,Strategy,"Singleplayer, exclusive, RTS, true exclusive",Game Factory Interactive,88.0,169.0,3.80,1,0,0
9994,2008-07-28,2008,1,552,"Action, Strategy","Multiplayer, Steam Cloud, First-Person, FPS, F...",Empires,86.0,1050.0,0.00,1,0,1
9995,2008-07-18,2008,1,612,RPG,"Singleplayer, Multiplayer, RPG, Action RPG, Ha...",Focus Home Interactive,72.0,95.0,3.60,1,0,0
9998,2008-07-11,2008,1,123,"Strategy, Board Games, Casual, Card, Education...","Singleplayer, Steam Achievements, 2D, puzzles,...","Electronic Arts, SlyGames, Taranau Aliaksei, R...",80.0,15.0,2.64,1,1,0
9999,2007-10-09,2007,4,306,"Action, Puzzle","Singleplayer, Steam Achievements, Atmospheric,...","Valve, Buka Entertainment, NVIDIA, CyberFront",98.0,81012.0,5.07,1,0,1

In [157]:
def spl(s):
    s = s.split('-')
    return int(s[1])

In [159]:
df['month'] = df['released'].apply(lambda x: spl(x))

In [160]:
df = df.drop('released', axis=1)
df

,source_window,playtime,suggestions_count,genres,tags,publishers,steam_review_percent,steam_review_count,steam_price_text,has_win,has_mac,has_linux,month
0,2013,74,450,Action,"Singleplayer, Steam Achievements, Multiplayer,...",Rockstar Games,79.0,56707.0,29.98,1,0,0,9
1,2015,43,688,"Action, RPG","Singleplayer, Full controller support, Atmosph...",CD PROJEKT RED,96.0,234151.0,29.99,1,0,0,5
2,2011,11,570,"Shooter, Puzzle","Singleplayer, Steam Achievements, Multiplayer,...","Electronic Arts, Valve",98.0,169118.0,5.79,1,0,1,4
3,2012,64,607,Shooter,"Steam Achievements, Multiplayer, Full controll...",Valve,86.0,2513715.0,0.00,1,0,1,8
5,2009,9,613,"Action, Shooter","Singleplayer, Steam Achievements, Multiplayer,...","Electronic Arts, Valve, Akella",97.0,225402.0,5.79,1,0,1,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,2008,1,520,Strategy,"Singleplayer, exclusive, RTS, true exclusive",Game Factory Interactive,88.0,169.0,3.80,1,0,0,9
9994,2008,1,552,"Action, Strategy","Multiplayer, Steam Cloud, First-Person, FPS, F...",Empires,86.0,1050.0,0.00,1,0,1,7
9995,2008,1,612,RPG,"Singleplayer, Multiplayer, RPG, Action RPG, Ha...",Focus Home Interactive,72.0,95.0,3.60,1,0,0,7
9998,2008,1,123,"Strategy, Board Games, Casual, Card, Education...","Singleplayer, Steam Achievements, 2D, puzzles,...","Electronic Arts, SlyGames, Taranau Aliaksei, R...",80.0,15.0,2.64,1,1,0,7
9999,2007,4,306,"Action, Puzzle","Singleplayer, Steam Achievements, Atmospheric,...","Valve, Buka Entertainment, NVIDIA, CyberFront",98.0,81012.0,5.07,1,0,1,10

In [161]:
lol = df.copy()
lol['genres'] = lol['genres'].str.split(', ')
df_exploded = lol.explode('genres')
lis = list(df_exploded['genres'].value_counts().head(10).index)
lis

['Indie',
 'Action',
 'Adventure',
 'Casual',
 'RPG',
 'Strategy',
 'Simulation',
 'Puzzle',
 'Shooter',
 'Arcade']

In [167]:
for i in lis:
    rn = 'is_' + i
    df[rn] = df['genres'].str.contains(i).astype(int)
df = df.drop('genres', axis=1)
df

,source_window,playtime,suggestions_count,tags,publishers,steam_review_percent,steam_review_count,steam_price_text,has_win,has_mac,...,is_Indie,is_Action,is_Adventure,is_Casual,is_RPG,is_Strategy,is_Simulation,is_Puzzle,is_Shooter,is_Arcade
0,2013,74,450,"Singleplayer, Steam Achievements, Multiplayer,...",Rockstar Games,79.0,56707.0,29.98,1,0,...,0,1,0,0,0,0,0,0,0,0
1,2015,43,688,"Singleplayer, Full controller support, Atmosph...",CD PROJEKT RED,96.0,234151.0,29.99,1,0,...,0,1,0,0,1,0,0,0,0,0
2,2011,11,570,"Singleplayer, Steam Achievements, Multiplayer,...","Electronic Arts, Valve",98.0,169118.0,5.79,1,0,...,0,0,0,0,0,0,0,1,1,0
3,2012,64,607,"Steam Achievements, Multiplayer, Full controll...",Valve,86.0,2513715.0,0.00,1,0,...,0,0,0,0,0,0,0,0,1,0
5,2009,9,613,"Singleplayer, Steam Achievements, Multiplayer,...","Electronic Arts, Valve, Akella",97.0,225402.0,5.79,1,0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,2008,1,520,"Singleplayer, exclusive, RTS, true exclusive",Game Factory Interactive,88.0,169.0,3.80,1,0,...,0,0,0,0,0,1,0,0,0,0
9994,2008,1,552,"Multiplayer, Steam Cloud, First-Person, FPS, F...",Empires,86.0,1050.0,0.00,1,0,...,0,1,0,0,0,1,0,0,0,0
9995,2008,1,612,"Singleplayer, Multiplayer, RPG, Action RPG, Ha...",Focus Home Interactive,72.0,95.0,3.60,1,0,...,0,0,0,0,1,0,0,0,0,0
9998,2008,1,123,"Singleplayer, Steam Achievements, 2D, puzzles,...","Electronic Arts, SlyGames, Taranau Aliaksei, R...",80.0,15.0,2.64,1,1,...,1,0,0,1,0,1,0,1,0,0
9999,2007,4,306,"Singleplayer, Steam Achievements, Atmospheric,...","Valve, Buka Entertainment, NVIDIA, CyberFront",98.0,81012.0,5.07,1,0,...,0,1,0,0,0,0,0,1,0,0

In [169]:
spis = ['Point-and-click', 'clown', 'zelda', 'Lovecraftian Horror', 'Period Piece', 'Lesbian', 'vive', 'dungeons', 'furry',
   'fan-translation', 'Slice Of Life', 'lgbtqia', 'roadtrip', 'claymation', 'bug']

In [171]:
for i in spis:
    rn = 'is_' + i
    df[rn] = df['tags'].str.contains(i).astype(int)
df = df.drop('tags', axis=1)
df

,source_window,playtime,suggestions_count,publishers,steam_review_percent,steam_review_count,steam_price_text,has_win,has_mac,has_linux,...,is_Lesbian,is_vive,is_dungeons,is_furry,is_fan-translation,is_Slice Of Life,is_lgbtqia,is_roadtrip,is_claymation,is_bug
0,2013,74,450,Rockstar Games,79.0,56707.0,29.98,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2015,43,688,CD PROJEKT RED,96.0,234151.0,29.99,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2011,11,570,"Electronic Arts, Valve",98.0,169118.0,5.79,1,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2012,64,607,Valve,86.0,2513715.0,0.00,1,0,1,...,0,0,0,0,0,0,0,0,0,0
5,2009,9,613,"Electronic Arts, Valve, Akella",97.0,225402.0,5.79,1,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,2008,1,520,Game Factory Interactive,88.0,169.0,3.80,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9994,2008,1,552,Empires,86.0,1050.0,0.00,1,0,1,...,0,0,0,0,0,0,0,0,0,0
9995,2008,1,612,Focus Home Interactive,72.0,95.0,3.60,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,2008,1,123,"Electronic Arts, SlyGames, Taranau Aliaksei, R...",80.0,15.0,2.64,1,1,0,...,0,0,0,0,0,0,0,0,0,0
9999,2007,4,306,"Valve, Buka Entertainment, NVIDIA, CyberFront",98.0,81012.0,5.07,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [173]:
lol = df.copy()
lol['publishers'] = lol['publishers'].str.split(', ')
df_exploded = lol.explode('publishers')
lis = list(df_exploded['publishers'].value_counts().head(15).index)
lis

['Devolver Digital',
 'THQ Nordic',
 'Bandai Namco Entertainment',
 'Plug In Digital',
 'Focus Home Interactive',
 'Daedalic Entertainment',
 'tinyBuild',
 'SEGA',
 'Ubisoft Entertainment',
 'Electronic Arts',
 'Kiss',
 'Square Enix',
 '505 Games',
 'Microsoft Studios',
 'Paradox Interactive']

In [175]:
for i in lis:
    rn = 'is_' + i
    df[rn] = df['publishers'].str.contains(i).astype(int)
df = df.drop('publishers', axis=1)
df

,source_window,playtime,suggestions_count,steam_review_percent,steam_review_count,steam_price_text,has_win,has_mac,has_linux,month,...,is_Daedalic Entertainment,is_tinyBuild,is_SEGA,is_Ubisoft Entertainment,is_Electronic Arts,is_Kiss,is_Square Enix,is_505 Games,is_Microsoft Studios,is_Paradox Interactive
0,2013,74,450,79.0,56707.0,29.98,1,0,0,9,...,0,0,0,0,0,0,0,0,0,0
1,2015,43,688,96.0,234151.0,29.99,1,0,0,5,...,0,0,0,0,0,0,0,0,0,0
2,2011,11,570,98.0,169118.0,5.79,1,0,1,4,...,0,0,0,0,1,0,0,0,0,0
3,2012,64,607,86.0,2513715.0,0.00,1,0,1,8,...,0,0,0,0,0,0,0,0,0,0
5,2009,9,613,97.0,225402.0,5.79,1,0,1,11,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,2008,1,520,88.0,169.0,3.80,1,0,0,9,...,0,0,0,0,0,0,0,0,0,0
9994,2008,1,552,86.0,1050.0,0.00,1,0,1,7,...,0,0,0,0,0,0,0,0,0,0
9995,2008,1,612,72.0,95.0,3.60,1,0,0,7,...,0,0,0,0,0,0,0,0,0,0
9998,2008,1,123,80.0,15.0,2.64,1,1,0,7,...,0,0,0,0,1,0,0,0,0,0
9999,2007,4,306,98.0,81012.0,5.07,1,0,1,10,...,0,0,0,0,0,0,0,0,0,0

In [177]:
df.to_csv('model_data.csv', index=False)

In [179]:
df.isna().sum()

source_window                    0
playtime                         0
suggestions_count                0
steam_review_percent             0
steam_review_count               0
steam_price_text                 0
has_win                          0
has_mac                          0
has_linux                        0
month                            0
is_Indie                         0
is_Action                        0
is_Adventure                     0
is_Casual                        0
is_RPG                           0
is_Strategy                      0
is_Simulation                    0
is_Puzzle                        0
is_Shooter                       0
is_Arcade                        0
is_Point-and-click               0
is_clown                         0
is_zelda                         0
is_Lovecraftian Horror           0
is_Period Piece                  0
is_Lesbian                       0
is_vive                          0
is_dungeons                      0
is_furry                         0
is_fan-translation               0
is_Slice Of Life                 0
is_lgbtqia                       0
is_roadtrip                      0
is_claymation                    0
is_bug                           0
is_Devolver Digital              0
is_THQ Nordic                    0
is_Bandai Namco Entertainment    0
is_Plug In Digital               0
is_Focus Home Interactive        0
is_Daedalic Entertainment        0
is_tinyBuild                     0
is_SEGA                          0
is_Ubisoft Entertainment         0
is_Electronic Arts               0
is_Kiss                          0
is_Square Enix                   0
is_505 Games                     0
is_Microsoft Studios             0
is_Paradox Interactive           0
dtype: int64