In [1]:
import pandas as pd
df = pd.read_csv('model_data.xls')
df

,source_window,playtime,suggestions_count,steam_review_percent,steam_review_count,steam_price_text,has_win,has_mac,has_linux,month,...,is_Daedalic Entertainment,is_tinyBuild,is_SEGA,is_Ubisoft Entertainment,is_Electronic Arts,is_Kiss,is_Square Enix,is_505 Games,is_Microsoft Studios,is_Paradox Interactive
0,2013,74,450,79.0,56707.0,29.98,1,0,0,9,...,0,0,0,0,0,0,0,0,0,0
1,2015,43,688,96.0,234151.0,29.99,1,0,0,5,...,0,0,0,0,0,0,0,0,0,0
2,2011,11,570,98.0,169118.0,5.79,1,0,1,4,...,0,0,0,0,1,0,0,0,0,0
3,2012,64,607,86.0,2513715.0,0.00,1,0,1,8,...,0,0,0,0,0,0,0,0,0,0
4,2009,9,613,97.0,225402.0,5.79,1,0,1,11,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7711,2008,1,520,88.0,169.0,3.80,1,0,0,9,...,0,0,0,0,0,0,0,0,0,0
7712,2008,1,552,86.0,1050.0,0.00,1,0,1,7,...,0,0,0,0,0,0,0,0,0,0
7713,2008,1,612,72.0,95.0,3.60,1,0,0,7,...,0,0,0,0,0,0,0,0,0,0
7714,2008,1,123,80.0,15.0,2.64,1,1,0,7,...,0,0,0,0,1,0,0,0,0,0
7715,2007,4,306,98.0,81012.0,5.07,1,0,1,10,...,0,0,0,0,0,0,0,0,0,0

In [2]:
import warnings

import matplotlib
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

y = df['steam_review_percent']
X_raw = df.drop('steam_review_percent', axis=1)
normalizer = MinMaxScaler()

X_real_norm_np = normalizer.fit_transform(X_raw)
X = pd.DataFrame(data=X_real_norm_np)
X.head()

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,0.315789,0.224924,0.256703,0.022554,0.227846,0.0,0.0,0.0,0.727273,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.421053,0.130699,0.392470,0.093142,0.227922,0.0,0.0,0.0,0.363636,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.210526,0.033435,0.325157,0.067272,0.044004,0.0,0.0,1.0,0.272727,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.263158,0.194529,0.346264,0.999961,0.000000,0.0,0.0,1.0,0.636364,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.105263,0.027356,0.349686,0.089662,0.044004,0.0,0.0,1.0,0.909091,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [3]:
from sklearn.linear_model import Lasso, Ridge
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.preprocessing import MinMaxScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.2)
lr = LinearRegression().fit(X_train, y_train)
print(f"Train: {mean_squared_error(y_train, lr.predict(X_train))}")
print(f"Test: {mean_squared_error(y_test, lr.predict(X_test))}")

Train: 173.5484281505029
Test: 167.82713084736764

In [4]:
ridge = Ridge(1).fit(X_train, y_train)
print("\nRidge")
print(f"Train: {mean_squared_error(y_train, ridge.predict(X_train))}")
print(f"Test: {mean_squared_error(y_test, ridge.predict(X_test))}")

Ridge
Train: 173.6872897827847
Test: 168.317164846383

Также хотелось бы провести еще один анализ, но так как мультиклассификацию мы не проходили, модель мы построим после ее изучения!